name: RDF syntax check
description: Iterates all RDF files in the repository and validates their syntax. It fails when an invalid file is detected.
author: AtomGraph
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  jena-version:
    description: 'The Jena version to set up'
    default: 4.7.0
  asf-archive:
    description: 'The Apache distribution URL'
    default: http://archive.apache.org/dist/

runs:
  using: "composite"
  steps:
    - name: Install Linux packages
      run: sudo apt-get update && sudo apt-get install curl
    - name: Download Jena
      run: curl -sS --fail "${{ asf-archive }}jena/binaries/apache-jena-$${{ jena-version }}.tar.gz" -o "${{ runner.temp }}/jena.tar.gz"
    - name: Unpack Jena
      run: tar -zxf jena.tar.gz
      working-directory: ${{ runner.temp }}
    - run: echo "$JENA_HOME/bin" >> $GITHUB_PATH
      env:
        JENA_HOME: "${{ runner.temp }}/apache-jena-$${{ jena-version }}"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Find RDF files and call riot for each of them
      run: find . \( -name "*.ttl" -o -name "*.trig" -o -name "*.nt" -o -name "*.nq" -o -name "*.rdf" -o -name "*.trix" -o -name "*.jsonld" \) -type f -print0 | while read -d $'\0' f; do echo "$f"; riot --validate "$f"; done